top_srcdir   = /Users/jim/src/asf/code/dev/httpd-trunk
top_builddir = /Users/jim/src/asf/code/dev/httpd-trunk
srcdir       = /Users/jim/src/asf/code/dev/httpd-trunk/modules/loggers
builddir     = /Users/jim/src/asf/code/dev/httpd-trunk/modules/loggers
VPATH        = /Users/jim/src/asf/code/dev/httpd-trunk/modules/loggers

include $(top_srcdir)/build/special.mk

