LIB=libproxy.a
OBJS=mod_proxy.o proxy_cache.o proxy_connect.o proxy_ftp.o proxy_http.o \
	proxy_util.o
INCDIR=../../include

all:	$(LIB)

$(LIB): $(OBJS)
	rm -f $@
	ar cr $@ $(OBJS)
	$(RANLIB) $@

.c.o:
	$(CC) -c $(INCLUDES) $(CFLAGS) $(SPACER) $<

clean:
	rm -f *.o $(LIB)

# We really don't expect end users to use this rule.  It works only with
# gcc, and rebuilds Makefile.tmpl.  You have to re-run Configure after
# using it.
depend:
	cp Makefile.tmpl Makefile.tmpl.bak \
	    && sed -ne '1,/^# DO NOT REMOVE/p' Makefile.tmpl > Makefile.new \
	    && gcc -MM $(INCLUDES) $(CFLAGS) *.c >> Makefile.new \
	    && sed -e '1,$$s: $(INCDIR)/: $$(INCDIR)/:g' Makefile.new \
		> Makefile.tmpl \
	    && rm Makefile.new

#Dependencies

$(OBJS): Makefile

# DO NOT REMOVE
mod_proxy.o: mod_proxy.c mod_proxy.h ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h ../../include/http_protocol.h \
 ../../include/explain.h ../../include/http_log.h
proxy_cache.o: proxy_cache.c mod_proxy.h ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h ../../include/http_protocol.h \
 ../../include/explain.h ../../include/http_log.h \
 ../../include/http_main.h ../../include/util_date.h \
 ../../include/multithread.h ../../include/md5.h
proxy_connect.o: proxy_connect.c mod_proxy.h ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h ../../include/http_protocol.h \
 ../../include/explain.h ../../include/http_log.h \
 ../../include/http_main.h
proxy_ftp.o: proxy_ftp.c mod_proxy.h ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h ../../include/http_protocol.h \
 ../../include/explain.h ../../include/http_main.h \
 ../standard/mod_mime.h
proxy_http.o: proxy_http.c mod_proxy.h ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h ../../include/http_protocol.h \
 ../../include/explain.h ../../include/http_log.h \
 ../../include/http_main.h ../../include/util_date.h
proxy_util.o: proxy_util.c mod_proxy.h ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h ../../include/http_protocol.h \
 ../../include/explain.h ../../include/http_main.h ../../include/md5.h \
 ../../include/multithread.h ../../include/http_log.h
