#!/bin/sh
#
# run-all-tests.sh -- unified runner for the two Python test suites under test/.
#
# Runs both pytest-based suites against the same built httpd:
#   1. pytest_suite/  -- the self-contained port of the classic Apache::Test
#      suite (core HTTP, modules, security CVEs, SSL, PHP). Run FIRST.
#   2. pyhttpd tests under modules/ -- httpd's own HTTP/2, mod_md, HTTP/1,
#      proxy and core tests (uses curl/nghttp/h2load; configured via
#      pyhttpd/config.ini).
#
# Both run against the same httpd; pytest_suite locates it via --apxs, while
# the pyhttpd tests read pyhttpd/config.ini (generated by httpd's configure).
#
# Usage:
#   ./run-all-tests.sh                 # run both suites (pytest_suite first)
#   ./run-all-tests.sh --only=pysuite  # run only pytest_suite
#   ./run-all-tests.sh --only=pyhttpd  # run only the pyhttpd modules/ tests
#   ./run-all-tests.sh --apxs /path/to/apxs   # override the httpd build
#   ./run-all-tests.sh -k status -v    # extra args pass through to BOTH pytests
#
# Environment overrides:
#   APXS       path to apxs (default: read from pyhttpd/config.ini, else $PATH)
#   PHP_FPM    path to php-fpm for pytest_suite's PHP tests (optional)
#   PYHTTPD_TARGETS  pyhttpd test paths (default: "modules")
#
set -eu

here="$(cd "$(dirname "$0")" && pwd)"
suite_dir="$here/pytest_suite"
config_ini="$here/pyhttpd/config.ini"

# Parse args once. Pull out --only and --apxs (space and = forms). Remaining
# arguments are split into:
#   flags     (start with '-', e.g. -v -k NAME -x): passed to BOTH pytests.
#   paths     (positional, e.g. tests/t/modules/...): these are pytest_suite
#             paths and go ONLY to pytest_suite. The pyhttpd side selects its
#             tests via PYHTTPD_TARGETS (or its auto-detected default), since a
#             pytest_suite path is meaningless there.
# A flag that takes a separate-word value (-k NAME) keeps the value as a flag.
only=""
apxs_opt=""
flags=""
paths=""
expect_apxs=0
expect_flagval=0
for arg in "$@"; do
    if [ "$expect_apxs" = "1" ]; then apxs_opt="$arg"; expect_apxs=0; continue; fi
    if [ "$expect_flagval" = "1" ]; then flags="$flags $arg"; expect_flagval=0; continue; fi
    case "$arg" in
        --only=*) only="${arg#--only=}" ;;
        --apxs)   expect_apxs=1 ;;
        --apxs=*) apxs_opt="${arg#--apxs=}" ;;
        -k|-m|-p) flags="$flags $arg"; expect_flagval=1 ;;  # take a value next
        -*)       flags="$flags $arg" ;;
        *)        paths="$paths $arg" ;;
    esac
done

# --- locate apxs (for pytest_suite) -----------------------------------------
if [ -z "$apxs_opt" ]; then
    if [ -n "${APXS:-}" ]; then
        apxs_opt="$APXS"
    elif [ -f "$config_ini" ]; then
        # Resolve apxs = ${exec_prefix}/bin/apxs from config.ini (simple expand).
        prefix=$(sed -n 's/^prefix = //p' "$config_ini" | head -1)
        apxs_opt="$prefix/bin/apxs"
    elif command -v apxs >/dev/null 2>&1; then
        apxs_opt="$(command -v apxs)"
    fi
fi

php_args=""
[ -n "${PHP_FPM:-}" ] && php_args="--php-fpm=$PHP_FPM"

rc=0

run_pysuite() {
    echo "=========================================================="
    echo "[1/2] pytest_suite (classic Apache::Test port)"
    echo "=========================================================="
    if [ -z "$apxs_opt" ]; then
        echo "run-all-tests.sh: ERROR: no apxs found for pytest_suite." >&2
        echo "  Pass --apxs=/path/to/apxs or set APXS=..." >&2
        return 2
    fi
    # runtests.sh handles venv + cgisock cleanup + flag assembly.
    # pytest_suite gets both the shared flags and any positional paths.
    # shellcheck disable=SC2086
    ( cd "$suite_dir" && ./runtests.sh --apxs="$apxs_opt" $php_args $flags $paths ) || return $?
}

run_pyhttpd() {
    echo "=========================================================="
    echo "[2/2] pyhttpd suites (modules/: http2, md, http1, proxy, core)"
    echo "=========================================================="
    if [ ! -f "$config_ini" ]; then
        echo "run-all-tests.sh: note: pyhttpd/config.ini not found;" >&2
        echo "  build httpd with its test config (configure) to run these." >&2
        return 0
    fi
    # pyhttpd tests use the system pytest + pyhttpd/config.ini (not our venv).
    if ! command -v pytest >/dev/null 2>&1; then
        echo "run-all-tests.sh: note: no 'pytest' on PATH for the pyhttpd suites; skipping." >&2
        return 0
    fi
    # Default to every modules/* dir whose conftest actually imports in this
    # environment -- so an optional missing dep (e.g. pyOpenSSL for md/) skips
    # just that area instead of aborting the whole pyhttpd run. Override with
    # PYHTTPD_TARGETS or by passing explicit paths.
    if [ -n "${PYHTTPD_TARGETS:-}" ]; then
        targets="$PYHTTPD_TARGETS"
    else
        targets=""
        for d in "$here"/modules/*/; do
            [ -d "$d" ] || continue
            name="modules/$(basename "$d")"
            if ( cd "$here" && pytest "$name" --co -q >/dev/null 2>&1 ); then
                targets="$targets $name"
            else
                echo "run-all-tests.sh: note: skipping $name (conftest not importable; missing dep?)" >&2
            fi
        done
    fi
    if [ -z "$targets" ]; then
        echo "run-all-tests.sh: note: no collectable pyhttpd module dirs; skipping." >&2
        return 0
    fi
    # pyhttpd gets the shared flags only; its test selection is $targets (a
    # pytest_suite positional path would be meaningless here).
    # shellcheck disable=SC2086
    ( cd "$here" && pytest $targets $flags ) || return $?
}

case "$only" in
    pysuite)  run_pysuite || rc=$? ;;
    pyhttpd)  run_pyhttpd || rc=$? ;;
    "")
        # Both, pytest_suite first. Keep going if the first fails so we get
        # results from both; report a non-zero overall rc if either failed.
        run_pysuite || rc=$?
        run_pyhttpd || rc=$?
        ;;
    *)
        echo "run-all-tests.sh: unknown --only=$only (use pysuite|pyhttpd)" >&2
        exit 2
        ;;
esac

echo "=========================================================="
[ "$rc" -eq 0 ] && echo "ALL SUITES PASSED" || echo "SOME TESTS FAILED (rc=$rc)"
echo "=========================================================="
exit "$rc"
