top_srcdir   = /Users/jim/src/asf/code/dev/httpd-trunk
top_builddir = /Users/jim/src/asf/code/dev/httpd-trunk
srcdir       = /Users/jim/src/asf/code/dev/httpd-trunk/modules/mappers
builddir     = /Users/jim/src/asf/code/dev/httpd-trunk/modules/mappers
VPATH        = /Users/jim/src/asf/code/dev/httpd-trunk/modules/mappers

include $(top_srcdir)/build/special.mk

