top_srcdir   = /Users/jim/src/asf/code/dev/httpd-trunk
top_builddir = /Users/jim/src/asf/code/dev/httpd-trunk
srcdir       = /Users/jim/src/asf/code/dev/httpd-trunk/server/mpm/event
builddir     = /Users/jim/src/asf/code/dev/httpd-trunk/server/mpm/event
VPATH        = /Users/jim/src/asf/code/dev/httpd-trunk/server/mpm/event
include $(top_srcdir)/build/special.mk
