CFLAGS=$(OPTIM) $(CFLAGS1) $(EXTRA_CFLAGS)
LIBS=$(EXTRA_LIBS) $(LIBS1)
INCLUDES=$(INCLUDES1) $(INCLUDES_DEPTH1) $(EXTRA_INCLUDES)
LDFLAGS=$(LDFLAGS1) $(EXTRA_LDFLAGS)
INCDIR=../include

LIB=libap.a

OBJS=ap_signal.o ap_slack.o ap_snprintf.o ap_strings.o ap_cpystrn.o \
	ap_execve.o

.c.o:
	$(CC) -c $(INCLUDES) $(CFLAGS) $(SPACER) $<

all: $(LIB)

clean:
	rm -f *.o *.a

$(OBJS): Makefile

$(LIB): $(OBJS)
	rm -f $@
	ar cr $@ $(OBJS)
	$(RANLIB) $@

# dependencies
ap_signal.o: $(INCDIR)/httpd.h
ap_slack.o: $(INCDIR)/httpd.h $(INCDIR)/http_log.h
ap_snprintf.o: $(INCDIR)/conf.h
ap_strings.o: $(INCDIR)/httpd.h
ap_cpystrn.o: $(INCDIR)/httpd.h
ap_execve.o: $(INCDIR)/httpd.h $(INCDIR)/http_log.h
