top_srcdir   = /Users/jim/src/asf/code/dev/httpd-trunk
top_builddir = /Users/jim/src/asf/code/dev/httpd-trunk
srcdir       = /Users/jim/src/asf/code/dev/httpd-trunk/modules/apreq
builddir     = /Users/jim/src/asf/code/dev/httpd-trunk/modules/apreq
VPATH        = /Users/jim/src/asf/code/dev/httpd-trunk/modules/apreq
include $(top_srcdir)/build/special.mk
