#!/bin/sh
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


if [ $# -lt 1 ]; then
    echo "usage: runtest /path/to/httpd" 1>&2
    exit 1
fi;

httpd="$1"
shift
pwd="`pwd`"


if [ $# = 0 ]; then
    list=conf/test*.conf
else
    list=$*
fi

pid=0
exitcode=0
trap 'kill $pid >/dev/null 2>&1; exit $exitcode' 0 1 2 3 15

for i in $list; do
    j=`echo $i | sed -e 's#.*/##' -e 's#\.conf$##'`
    echo ''
    echo "==== $j ===="
    f="$pwd/conf/$j.conf"
    grep '^##' $f
    $httpd -f $f
    # such a pain to wait for the pid file to be created
    sleep 1
    pid="`cat logs/httpd.pid`"

    sh bin/$j

    # such a pain to know if it has finished
    kill $pid
    sleep 1
    while kill -0 $pid >/dev/null 2>&1; do
	sleep 1
    done
done
