top_srcdir   = /home/ganwang/httpd/httpd
top_builddir = /home/ganwang/httpd/httpd
srcdir       = /home/ganwang/httpd/httpd/modules/loggers
builddir     = /home/ganwang/httpd/httpd/modules/loggers
VPATH        = /home/ganwang/httpd/httpd/modules/loggers

include $(top_srcdir)/build/special.mk

