top_srcdir   = /home/ganwang/Documents/httpd
top_builddir = /home/ganwang/Documents/httpd
srcdir       = /home/ganwang/Documents/httpd/server/mpm/worker
builddir     = /home/ganwang/Documents/httpd/server/mpm/worker
VPATH        = /home/ganwang/Documents/httpd/server/mpm/worker

include $(top_srcdir)/build/special.mk
