top_srcdir   = /home/ganwang/httpd/httpd
top_builddir = /home/ganwang/httpd/httpd
srcdir       = /home/ganwang/httpd/httpd/modules/generators
builddir     = /home/ganwang/httpd/httpd/modules/generators
VPATH        = /home/ganwang/httpd/httpd/modules/generators

include $(top_srcdir)/build/special.mk

