top_srcdir   = /home/ganwang/httpd/httpd
top_builddir = /home/ganwang/httpd/httpd
srcdir       = /home/ganwang/httpd/httpd/modules/echo
builddir     = /home/ganwang/httpd/httpd/modules/echo
VPATH        = /home/ganwang/httpd/httpd/modules/echo

include $(top_srcdir)/build/special.mk

