# Apache makefile template (well, suffix).

# This is combined with the information in the "Configuration" file
# by the configure script to make the actual Makefile.

CFLAGS=$(OPTIM) $(CFLAGS1) $(EXTRA_CFLAGS)
LIBS=$(EXTRA_LIBS) $(LIBS1) -lap
INCLUDES=$(INCLUDES1) $(INCLUDES_DEPTH1) $(EXTRA_INCLUDES)
LDFLAGS=$(LDFLAGS1) $(EXTRA_LDFLAGS) -L../ap
INCDIR=../include

TARGETS=htpasswd htdigest rotatelogs logresolve ab

OBJS=htpasswd.o htdigest.o rotatelogs.o logresolve.o ab.o

.c.o: 
	$(CC) -c $(CFLAGS) $(INCLUDES) $<

all: $(TARGETS)

htpasswd: htpasswd.o
	$(CC) $(CFLAGS) htpasswd.o -o htpasswd $(LDFLAGS) $(LIBS)

htdigest: htdigest.o
	$(CC) $(CFLAGS) htdigest.o -o htdigest $(LDFLAGS) $(LIBS)

rotatelogs: rotatelogs.o
	$(CC) $(INCLUDES) $(CFLAGS) rotatelogs.o -o rotatelogs $(LDFLAGS) $(LIBS)

logresolve: logresolve.o
	$(CC) $(INCLUDES) $(CFLAGS) logresolve.o -o logresolve $(LDFLAGS) $(LIBS)

ab: ab.o
	$(CC) $(INCLUDES) $(CFLAGS) ab.o -o ab $(LDFLAGS) $(LIBS)

clean:
	rm -f $(TARGETS) *.o

# We really don't expect end users to use this rule.  It works only with
# gcc, and rebuilds Makefile.tmpl.  You have to re-run Configure after
# using it.
depend:
	cp Makefile.tmpl Makefile.tmpl.bak \
	    && sed -ne '1,/^# DO NOT REMOVE/p' Makefile.tmpl > Makefile.new \
	    && gcc -MM $(INCLUDES) $(CFLAGS) *.c >> Makefile.new \
	    && sed -e '1,$$s: $(INCDIR)/: $$(INCDIR)/:g' Makefile.new \
		> Makefile.tmpl \
	    && rm Makefile.new

#Dependencies

$(OBJS): Makefile

# DO NOT REMOVE
cls.o: cls.c
htdigest.o: htdigest.c ../main/md5c.c $(INCDIR)/conf.h \
 ../os/unix/os.h $(INCDIR)/hsregex.h $(INCDIR)/md5.h
htpasswd.o: htpasswd.c
logresolve.o: logresolve.c
rotatelogs.o: rotatelogs.c
suexec.o: suexec.c suexec.h
