top_srcdir   = /Users/jim/src/asf/code/dev/svn/httpd-2.1
top_builddir = /Users/jim/src/asf/code/dev/svn/httpd-2.1
srcdir       = /Users/jim/src/asf/code/dev/svn/httpd-2.1/modules/debug
builddir     = /Users/jim/src/asf/code/dev/svn/httpd-2.1/modules/debug
VPATH        = /Users/jim/src/asf/code/dev/svn/httpd-2.1/modules/debug
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
