top_srcdir   = /Users/jim/src/asf/code/dev/httpd-trunk
top_builddir = /Users/jim/src/asf/code/dev/httpd-trunk
srcdir       = /Users/jim/src/asf/code/dev/httpd-trunk/os/unix
builddir     = /Users/jim/src/asf/code/dev/httpd-trunk/os/unix
VPATH        = /Users/jim/src/asf/code/dev/httpd-trunk/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
