/* modules.c --- automatically generated by Apache
 * configuration script.  DO NOT HAND EDIT!!!!!
 */

#include "../httpd.h"
#include "../http_config.h"

extern module core_module;
extern module dll_module;

module *prelinked_modules[] = {
  &core_module,
  &dll_module,
  NULL
};
module *preloaded_modules[] = {
  &core_module,
  &dll_module,
  NULL
};
