top_srcdir   = /Users/jim/src/asf/code/dev/httpd-trunk
top_builddir = /Users/jim/src/asf/code/dev/httpd-trunk
srcdir       = /Users/jim/src/asf/code/dev/httpd-trunk/modules/ldap
builddir     = /Users/jim/src/asf/code/dev/httpd-trunk/modules/ldap
VPATH        = /Users/jim/src/asf/code/dev/httpd-trunk/modules/ldap
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
