#!/bin/sh
##
## fp2rp -- convert a standard forward path to a reverse dotted path
##
if [ "x$1" = x. ]; then
    rp="."
else
    rp=""
    for pe in `echo $1 | sed -e 's:/: :'`; do
	rp="../$rp"
    done
fi
echo $rp | sed -e 's:/$::'
