#!/bin/sh
# Look for program[s] somewhere in $PATH.
#
# Options:
#  -s
#    Do not print out full pathname. (silent)
#  -pPATHNAME
#    Look in PATHNAME instead of $PATH
#
# Usage:
#  PrintPath [-s] [-pPATHNAME] program [program ...]
#
# Blame Jim; he wrote it (with major OS2 help from Brian H.)
#
# This script falls under the Apache License.
# See http://www.apache.org/docs/LICENSE
#
##
# Some "constants"
##
pathname=$PATH
echo="yes"

##
# Parse command line
##
for args in $*
do
    case $args in
	-s  ) echo="no" ;;
	-p* ) pathname="`echo $args | sed 's/^..//'`" ;;
	*   ) programs="$programs $args" ;;
    esac
done

for program in $programs
do
    for path in `echo $pathname |
     sed 's/^;/.;/
	  s/;;/;.;/g
	  s/;$/;./
	  s/;/ /g
	  s/\\\\/\\//g' `
    do
	if [ -r $path/$program.exe ] && [ ! -d $path/$program.exe ]; then
	    if [ "$echo" = "yes" ]; then
		echo $path/$program.exe
	    fi
	    exit 0
	fi
    done
done
exit 1

