top_srcdir   = /Users/jim/src/asf/code/dev/httpd-trunk
top_builddir = /Users/jim/src/asf/code/dev/httpd-trunk
srcdir       = /Users/jim/src/asf/code/dev/httpd-trunk/modules/http
builddir     = /Users/jim/src/asf/code/dev/httpd-trunk/modules/http
VPATH        = /Users/jim/src/asf/code/dev/httpd-trunk/modules/http

include $(top_srcdir)/build/special.mk

