top_srcdir   = /Users/jim/src/asf/code/dev/httpd-trunk
top_builddir = /Users/jim/src/asf/code/dev/httpd-trunk
srcdir       = /Users/jim/src/asf/code/dev/httpd-trunk/modules/arch/unix
builddir     = /Users/jim/src/asf/code/dev/httpd-trunk/modules/arch/unix
VPATH        = /Users/jim/src/asf/code/dev/httpd-trunk/modules/arch/unix

include $(top_srcdir)/build/special.mk

