#define IDD_APSRVMON_DIALOG             101
#define IDD_ABOUTBOX                    102
#define IDS_APP_TITLE                   103
#define IDM_RESTORE                     104
#define IDM_ABOUT                       105
#define IDM_EXIT                        106
#define IDI_APSRVMONM                   107
#define IDI_APSRVMON                    108
#define IDI_APSMALL                     109
#define IDC_APSRVMON                    110
#define IDS_VERSION_ERROR               111
#define IDS_VER_INFO_LANG               112
#define IDR_MAINFRAME                   128
#define IDI_ICOSTOP                     129
#define IDI_ICORUN                      130
#define IDC_STATBAR                     134
#define DLG_VERFIRST                    140
#define IDC_COMPANY                     140
#define IDC_FILEDESC                    141
#define IDC_PRODVER                     142
#define IDC_COPYRIGHT                   143
#define IDC_OSVERSION                   144
#define IDC_TRADEMARK                   145
#define DLG_VERLAST                     145
#define IDC_LABEL                       146
#define IDB_BMPSTOP                     155
#define IDB_BMPRUN                      156
#define IDB_BMPHEADER                   158
#define IDL_SERVICES                    1001
#define IDL_STDOUT                      1002
#define IDC_SSTART                      1003
#define IDC_SSTOP                       1004
#define IDC_SRESTART                    1005
#define IDC_SABOUT                      1006
#define IDC_STATIC                      -1
