#define IDD_DLGSERVICES		            101
#define IDS_APMONITORTITLE              102
#define IDS_APMONITORCLASS              103
#define IDM_RESTORE                     104
#define IDM_EXIT                        105
#define IDI_APSRVMON                    106
#define IDI_ICOSTOP                     107
#define IDI_ICORUN                      108
#define IDC_STATBAR                     109
#define IDC_SSTATUS                     110
#define IDB_BMPSTOP                     111
#define IDB_BMPRUN                      112
#define IDB_BMPHEADER                   113
#define IDL_SERVICES                    114
#define IDL_STDOUT                      115
#define IDC_SSTART                      116
#define IDC_SSTOP                       117
#define IDC_SRESTART                    118
#define IDC_SEXIT                       119
#define IDC_STATIC                      -1
