top_srcdir   = /home/ganwang/httpd/httpd
top_builddir = /home/ganwang/httpd/httpd
srcdir       = /home/ganwang/httpd/httpd/modules/aaa
builddir     = /home/ganwang/httpd/httpd/modules/aaa
VPATH        = /home/ganwang/httpd/httpd/modules/aaa

include $(top_srcdir)/build/special.mk

