top_srcdir   = /home/ganwang/httpd/httpd
top_builddir = /home/ganwang/httpd/httpd
srcdir       = /home/ganwang/httpd/httpd/modules/cluster
builddir     = /home/ganwang/httpd/httpd/modules/cluster
VPATH        = /home/ganwang/httpd/httpd/modules/cluster
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
