top_srcdir   = /home/ganwang/Documents/httpd
top_builddir = /home/ganwang/Documents/httpd
srcdir       = /home/ganwang/Documents/httpd/modules/lua
builddir     = /home/ganwang/Documents/httpd/modules/lua
VPATH        = /home/ganwang/Documents/httpd/modules/lua
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
