top_srcdir   = /home/ganwang/Documents/httpd
top_builddir = /home/ganwang/Documents/httpd
srcdir       = /home/ganwang/Documents/httpd/os
builddir     = /home/ganwang/Documents/httpd/os
VPATH        = /home/ganwang/Documents/httpd/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
