top_srcdir   = /home/ganwang/Documents/httpd
top_builddir = /home/ganwang/Documents/httpd
srcdir       = /home/ganwang/Documents/httpd/srclib
builddir     = /home/ganwang/Documents/httpd/srclib
VPATH        = /home/ganwang/Documents/httpd/srclib

BUILD_SUBDIRS = $(AP_BUILD_SRCLIB_DIRS)
CLEAN_SUBDIRS = $(AP_CLEAN_SRCLIB_DIRS)

include $(top_builddir)/build/rules.mk
