top_srcdir   = /Users/jim/src/asf/code/dev/httpd-trunk
top_builddir = /Users/jim/src/asf/code/dev/httpd-trunk
srcdir       = /Users/jim/src/asf/code/dev/httpd-trunk/modules/metadata
builddir     = /Users/jim/src/asf/code/dev/httpd-trunk/modules/metadata
VPATH        = /Users/jim/src/asf/code/dev/httpd-trunk/modules/metadata

include $(top_srcdir)/build/special.mk

