# default Makefile.tmpl to force Configure to create a Makefile

# We really don't expect end users to use this rule.  It works only with
# gcc, and rebuilds Makefile.tmpl.  You have to re-run Configure after
# using it.
depend:
	cp Makefile.tmpl Makefile.tmpl.bak \
	    && sed -ne '1,/^# DO NOT REMOVE/p' Makefile.tmpl > Makefile.new \
	    && gcc -MM $(INCLUDES) $(CFLAGS) *.c >> Makefile.new \
	    && sed -e '1,$$s: $(INCDIR)/: $$(INCDIR)/:g' \
	           -e '1,$$s: $(OSDIR)/: $$(OSDIR)/:g' Makefile.new \
		> Makefile.tmpl \
	    && rm Makefile.new

#Dependencies

$(OBJS): Makefile

# DO NOT REMOVE
mod_example.o: mod_example.c $(INCDIR)/httpd.h \
 $(INCDIR)/conf.h $(OSDIR)/os.h $(INCDIR)/alloc.h \
 $(INCDIR)/buff.h $(INCDIR)/ap.h $(INCDIR)/util_uri.h \
 $(INCDIR)/http_config.h $(INCDIR)/http_core.h \
 $(INCDIR)/http_log.h $(INCDIR)/http_main.h \
 $(INCDIR)/http_protocol.h $(INCDIR)/util_script.h
