# default Makefile.tmpl to force Configure to create a Makefile

# We really don't expect end users to use this rule.  It works only with
# gcc, and rebuilds Makefile.tmpl.  You have to re-run Configure after
# using it.
depend:
	sed -ne '1,/^# DO NOT REMOVE/p' Makefile.tmpl > Makefile.new \
	    && $(CC) -MM $(INCLUDES) $(CFLAGS) *.c >> Makefile.new \
	    && mv Makefile.tmpl Makefile.tmpl.bak \
	    && mv Makefile.new Makefile.tmpl

#Dependencies

$(OBJS): Makefile

# DO NOT REMOVE
mod_example.o: mod_example.c ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h ../../include/http_core.h \
 ../../include/http_log.h ../../include/http_main.h \
 ../../include/http_protocol.h ../../include/util_script.h
