LIB=libproxy.a
OBJS=mod_proxy.o proxy_cache.o proxy_connect.o proxy_ftp.o proxy_http.o \
proxy_util.o

all:	$(LIB)

$(LIB): $(OBJS)
	rm -f $@
	ar cr $@ $(OBJS)
	$(RANLIB) $@

.c.o:
	$(CC) -c $(INCLUDES) $(CFLAGS) $(SPACER) $<

clean:
	rm -f *.o $(LIB)

$(OBJS): Makefile

# dependencies
$(OBJS): mod_proxy.h $(INCDIR)/httpd.h $(INCDIR)/http_config.h $(INCDIR)/http_protocol.h
proxy_cache.o proxy_connect.o proxy_http.o proxy_util.o: $(INCDIR)/http_main.h
proxy_cache.o proxy_connect.o proxy_http.o: $(INCDIR)/http_log.h
proxy_cache.o proxy_http.o: $(INCDIR)/util_date.h
proxy_cache.o proxy_util.o: $(INCDIR)/md5.h
proxy_ftp.o: $(INCDIR)/http_main.h ../standard/mod_mime.h
