top_srcdir   = /Users/jim/src/asf/code/dev/httpd-trunk
top_builddir = /Users/jim/src/asf/code/dev/httpd-trunk
srcdir       = /Users/jim/src/asf/code/dev/httpd-trunk/srclib
builddir     = /Users/jim/src/asf/code/dev/httpd-trunk/srclib
VPATH        = /Users/jim/src/asf/code/dev/httpd-trunk/srclib

BUILD_SUBDIRS = $(AP_BUILD_SRCLIB_DIRS)
CLEAN_SUBDIRS = $(AP_CLEAN_SRCLIB_DIRS)

include $(top_builddir)/build/rules.mk
