#include <stdio.h>

/* generate a table of 256 values, where certain characters are
 * marked "interesting"... for the uri parsing process.
 */

void main(void)
{
    int i;
    char *value;

    printf("/* this file is automatically generated by "
	    "gen_uri_delims, do not edit */\n");
    for (i = 0; i < 256; ++i) {
	switch (i) {
	case ':': 	value = "T_COLON";	break;
	case '/': 	value = "T_SLASH";	break;
	case '?': 	value = "T_QUESTION";	break;
	case '#': 	value = "T_HASH";	break;
	case '\0': 	value = "T_NUL";	break;
	default:	value = "0";		break;
	}
	printf("%s%c\n", value, (i < 255) ? ',' : ' ');
    }
    exit(0);
}
