# Apache makefile suffix for core files

# This is combined with the information in the "Configuration" file
# by the configure script to make the actual Makefile.

CFLAGS=$(OPTIM) $(CFLAGS1) $(EXTRA_CFLAGS)
LIBS=$(EXTRA_LIBS) $(LIBS1)
INCLUDES=$(INCLUDES1) $(INCLUDES_DEPTH1) $(EXTRA_INCLUDES)
LDFLAGS=$(LDFLAGS1) $(EXTRA_LDFLAGS)
INCDIR=../include

OBJS= alloc.o http_main.o http_core.o http_config.o http_request.o \
  http_log.o http_protocol.o rfc1413.o util.o util_script.o buff.o \
  md5c.o util_md5.o explain.o http_bprintf.o util_date.o \
  fnmatch.o http_vhost.o

.c.o:
	$(CC) -c $(INCLUDES) $(CFLAGS) $(SPACER) $<

LIB=	libmain.a

all: $(LIB)

$(LIB): $(OBJS)
	rm -f $@
	ar cr $@ $(OBJS)
	$(RANLIB) $@

clean:
	rm -f *.o $(LIB)

# Work around broken compilers
http_bprintf.o: http_bprintf.c
	$(CC) -c $(INCLUDES) $(CFLAGS) $(BROKEN_BPRINTF_FLAGS) http_bprintf.c

# We really don't expect end users to use this rule.  It works only with
# gcc, and rebuilds Makefile.tmpl.  You have to re-run Configure after
# using it.
depend:
	cp Makefile.tmpl Makefile.tmpl.bak \
	    && sed -ne '1,/^# DO NOT REMOVE/p' Makefile.tmpl > Makefile.new \
	    && gcc -MM $(INCLUDES) $(CFLAGS) *.c >> Makefile.new \
	    && sed -e '1,$$s: $(INCDIR)/: $$(INCDIR)/:g' Makefile.new \
		> Makefile.tmpl \
	    && rm Makefile.new

#Dependencies

$(OBJS): Makefile

# DO NOT REMOVE
alloc.o: alloc.c $(INCDIR)/httpd.h $(INCDIR)/conf.h ../os/unix/os.h \
 $(INCDIR)/hsregex.h $(INCDIR)/alloc.h $(INCDIR)/buff.h \
 $(INCDIR)/ap.h $(INCDIR)/multithread.h $(INCDIR)/http_log.h
buff.o: buff.c $(INCDIR)/httpd.h $(INCDIR)/conf.h ../os/unix/os.h \
 $(INCDIR)/hsregex.h $(INCDIR)/alloc.h $(INCDIR)/buff.h \
 $(INCDIR)/ap.h $(INCDIR)/http_main.h $(INCDIR)/http_log.h
explain.o: explain.c $(INCDIR)/httpd.h $(INCDIR)/conf.h \
 ../os/unix/os.h $(INCDIR)/hsregex.h $(INCDIR)/alloc.h \
 $(INCDIR)/buff.h $(INCDIR)/ap.h $(INCDIR)/explain.h
fnmatch.o: fnmatch.c $(INCDIR)/fnmatch.h
http_bprintf.o: http_bprintf.c $(INCDIR)/httpd.h $(INCDIR)/conf.h \
 ../os/unix/os.h $(INCDIR)/hsregex.h $(INCDIR)/alloc.h \
 $(INCDIR)/buff.h $(INCDIR)/ap.h
http_config.o: http_config.c $(INCDIR)/httpd.h $(INCDIR)/conf.h \
 ../os/unix/os.h $(INCDIR)/hsregex.h $(INCDIR)/alloc.h \
 $(INCDIR)/buff.h $(INCDIR)/ap.h $(INCDIR)/http_config.h \
 $(INCDIR)/http_core.h $(INCDIR)/http_log.h \
 $(INCDIR)/http_request.h $(INCDIR)/http_conf_globals.h \
 $(INCDIR)/http_vhost.h $(INCDIR)/explain.h
http_core.o: http_core.c $(INCDIR)/httpd.h $(INCDIR)/conf.h \
 ../os/unix/os.h $(INCDIR)/hsregex.h $(INCDIR)/alloc.h \
 $(INCDIR)/buff.h $(INCDIR)/ap.h $(INCDIR)/http_config.h \
 $(INCDIR)/http_core.h $(INCDIR)/http_protocol.h \
 $(INCDIR)/http_request.h $(INCDIR)/http_conf_globals.h \
 $(INCDIR)/http_vhost.h $(INCDIR)/http_main.h $(INCDIR)/http_log.h \
 $(INCDIR)/rfc1413.h $(INCDIR)/util_md5.h $(INCDIR)/md5.h \
 $(INCDIR)/scoreboard.h $(INCDIR)/fnmatch.h
http_log.o: http_log.c $(INCDIR)/httpd.h $(INCDIR)/conf.h \
 ../os/unix/os.h $(INCDIR)/hsregex.h $(INCDIR)/alloc.h \
 $(INCDIR)/buff.h $(INCDIR)/ap.h $(INCDIR)/http_config.h \
 $(INCDIR)/http_core.h $(INCDIR)/http_log.h $(INCDIR)/http_main.h
http_main.o: http_main.c $(INCDIR)/httpd.h $(INCDIR)/conf.h \
 ../os/unix/os.h $(INCDIR)/hsregex.h $(INCDIR)/alloc.h \
 $(INCDIR)/buff.h $(INCDIR)/ap.h $(INCDIR)/http_main.h \
 $(INCDIR)/http_log.h $(INCDIR)/http_config.h \
 $(INCDIR)/http_protocol.h $(INCDIR)/http_request.h \
 $(INCDIR)/http_conf_globals.h $(INCDIR)/http_core.h \
 $(INCDIR)/http_vhost.h $(INCDIR)/util_script.h \
 $(INCDIR)/scoreboard.h $(INCDIR)/multithread.h $(INCDIR)/explain.h
http_protocol.o: http_protocol.c $(INCDIR)/httpd.h $(INCDIR)/conf.h \
 ../os/unix/os.h $(INCDIR)/hsregex.h $(INCDIR)/alloc.h \
 $(INCDIR)/buff.h $(INCDIR)/ap.h $(INCDIR)/http_config.h \
 $(INCDIR)/http_core.h $(INCDIR)/http_protocol.h \
 $(INCDIR)/http_main.h $(INCDIR)/http_request.h \
 $(INCDIR)/http_vhost.h $(INCDIR)/http_log.h $(INCDIR)/util_date.h \
 $(INCDIR)/http_conf_globals.h
http_request.o: http_request.c $(INCDIR)/httpd.h $(INCDIR)/conf.h \
 ../os/unix/os.h $(INCDIR)/hsregex.h $(INCDIR)/alloc.h \
 $(INCDIR)/buff.h $(INCDIR)/ap.h $(INCDIR)/http_config.h \
 $(INCDIR)/http_request.h $(INCDIR)/http_core.h \
 $(INCDIR)/http_protocol.h $(INCDIR)/http_log.h \
 $(INCDIR)/http_main.h $(INCDIR)/scoreboard.h $(INCDIR)/fnmatch.h
http_vhost.o: http_vhost.c $(INCDIR)/httpd.h $(INCDIR)/conf.h \
 ../os/unix/os.h $(INCDIR)/hsregex.h $(INCDIR)/alloc.h \
 $(INCDIR)/buff.h $(INCDIR)/ap.h $(INCDIR)/http_config.h \
 $(INCDIR)/http_conf_globals.h $(INCDIR)/http_log.h \
 $(INCDIR)/http_vhost.h $(INCDIR)/http_protocol.h
md5c.o: md5c.c $(INCDIR)/conf.h ../os/unix/os.h $(INCDIR)/hsregex.h \
 $(INCDIR)/md5.h
rfc1413.o: rfc1413.c $(INCDIR)/httpd.h $(INCDIR)/conf.h \
 ../os/unix/os.h $(INCDIR)/hsregex.h $(INCDIR)/alloc.h \
 $(INCDIR)/buff.h $(INCDIR)/ap.h $(INCDIR)/http_log.h \
 $(INCDIR)/rfc1413.h $(INCDIR)/http_main.h
util.o: util.c $(INCDIR)/httpd.h $(INCDIR)/conf.h ../os/unix/os.h \
 $(INCDIR)/hsregex.h $(INCDIR)/alloc.h $(INCDIR)/buff.h \
 $(INCDIR)/ap.h $(INCDIR)/http_conf_globals.h $(INCDIR)/http_log.h
util_date.o: util_date.c $(INCDIR)/conf.h ../os/unix/os.h \
 $(INCDIR)/hsregex.h $(INCDIR)/util_date.h
util_md5.o: util_md5.c $(INCDIR)/httpd.h $(INCDIR)/conf.h \
 ../os/unix/os.h $(INCDIR)/hsregex.h $(INCDIR)/alloc.h \
 $(INCDIR)/buff.h $(INCDIR)/ap.h $(INCDIR)/util_md5.h \
 $(INCDIR)/md5.h
util_script.o: util_script.c $(INCDIR)/httpd.h $(INCDIR)/conf.h \
 ../os/unix/os.h $(INCDIR)/hsregex.h $(INCDIR)/alloc.h \
 $(INCDIR)/buff.h $(INCDIR)/ap.h $(INCDIR)/http_config.h \
 $(INCDIR)/http_conf_globals.h $(INCDIR)/http_main.h \
 $(INCDIR)/http_log.h $(INCDIR)/http_protocol.h \
 $(INCDIR)/http_core.h $(INCDIR)/http_request.h \
 $(INCDIR)/util_script.h $(INCDIR)/util_date.h
