# Apache makefile suffix for core files

# This is combined with the information in the "Configuration" file
# by the configure script to make the actual Makefile.

CFLAGS=$(OPTIM) $(CFLAGS1) $(EXTRA_CFLAGS)
LIBS=$(EXTRA_LIBS) $(LIBS1)
INCLUDES=$(INCLUDES1) $(INCLUDES_DEPTH1) $(EXTRA_INCLUDES)
LDFLAGS=$(LDFLAGS1) $(EXTRA_LDFLAGS)
INCDIR=../include

OBJS= alloc.o http_main.o http_core.o http_config.o http_request.o \
  http_log.o http_protocol.o rfc1413.o util.o util_script.o buff.o \
  md5c.o util_md5.o explain.o http_bprintf.o util_date.o \
  fnmatch.o http_vhost.o

.c.o:
	$(CC) -c $(INCLUDES) $(CFLAGS) $(SPACER) $<

LIB=	libmain.a

all: $(LIB)

$(LIB): $(OBJS)
	rm -f $@
	ar cr $@ $(OBJS)
	$(RANLIB) $@

clean:
	rm -f *.o $(LIB)

# Work around broken compilers
http_bprintf.o: http_bprintf.c
	$(CC) -c $(INCLUDES) $(CFLAGS) $(BROKEN_BPRINTF_FLAGS) http_bprintf.c

# We really don't expect end users to use this rule.  It works only with
# gcc, and rebuilds Makefile.tmpl.  You have to re-run Configure after
# using it.
depend:
	sed -ne '1,/^# DO NOT REMOVE/p' Makefile.tmpl > Makefile.new \
	    && $(CC) -MM $(INCLUDES) $(CFLAGS) *.c >> Makefile.new \
	    && mv Makefile.tmpl Makefile.tmpl.bak \
	    && mv Makefile.new Makefile.tmpl

#Dependencies

$(OBJS): Makefile

# DO NOT REMOVE
alloc.o: alloc.c ../include/httpd.h ../include/conf.h ../os/unix/os.h \
 ../include/hsregex.h ../include/alloc.h ../include/buff.h \
 ../include/ap.h ../include/multithread.h ../include/http_log.h
buff.o: buff.c ../include/httpd.h ../include/conf.h ../os/unix/os.h \
 ../include/hsregex.h ../include/alloc.h ../include/buff.h \
 ../include/ap.h ../include/http_main.h ../include/http_log.h
explain.o: explain.c ../include/httpd.h ../include/conf.h \
 ../os/unix/os.h ../include/hsregex.h ../include/alloc.h \
 ../include/buff.h ../include/ap.h ../include/explain.h
fnmatch.o: fnmatch.c ../include/fnmatch.h
http_bprintf.o: http_bprintf.c ../include/httpd.h ../include/conf.h \
 ../os/unix/os.h ../include/hsregex.h ../include/alloc.h \
 ../include/buff.h ../include/ap.h
http_config.o: http_config.c ../include/httpd.h ../include/conf.h \
 ../os/unix/os.h ../include/hsregex.h ../include/alloc.h \
 ../include/buff.h ../include/ap.h ../include/http_config.h \
 ../include/http_core.h ../include/http_log.h \
 ../include/http_request.h ../include/http_conf_globals.h \
 ../include/http_vhost.h ../include/explain.h
http_core.o: http_core.c ../include/httpd.h ../include/conf.h \
 ../os/unix/os.h ../include/hsregex.h ../include/alloc.h \
 ../include/buff.h ../include/ap.h ../include/http_config.h \
 ../include/http_core.h ../include/http_protocol.h \
 ../include/http_request.h ../include/http_conf_globals.h \
 ../include/http_vhost.h ../include/http_main.h ../include/http_log.h \
 ../include/rfc1413.h ../include/util_md5.h ../include/md5.h \
 ../include/scoreboard.h ../include/fnmatch.h
http_log.o: http_log.c ../include/httpd.h ../include/conf.h \
 ../os/unix/os.h ../include/hsregex.h ../include/alloc.h \
 ../include/buff.h ../include/ap.h ../include/http_config.h \
 ../include/http_core.h ../include/http_log.h ../include/http_main.h
http_main.o: http_main.c ../include/httpd.h ../include/conf.h \
 ../os/unix/os.h ../include/hsregex.h ../include/alloc.h \
 ../include/buff.h ../include/ap.h ../include/http_main.h \
 ../include/http_log.h ../include/http_config.h \
 ../include/http_protocol.h ../include/http_request.h \
 ../include/http_conf_globals.h ../include/http_core.h \
 ../include/http_vhost.h ../include/util_script.h \
 ../include/scoreboard.h ../include/multithread.h ../include/explain.h
http_protocol.o: http_protocol.c ../include/httpd.h ../include/conf.h \
 ../os/unix/os.h ../include/hsregex.h ../include/alloc.h \
 ../include/buff.h ../include/ap.h ../include/http_config.h \
 ../include/http_core.h ../include/http_protocol.h \
 ../include/http_main.h ../include/http_request.h \
 ../include/http_vhost.h ../include/http_log.h ../include/util_date.h \
 ../include/http_conf_globals.h
http_request.o: http_request.c ../include/httpd.h ../include/conf.h \
 ../os/unix/os.h ../include/hsregex.h ../include/alloc.h \
 ../include/buff.h ../include/ap.h ../include/http_config.h \
 ../include/http_request.h ../include/http_core.h \
 ../include/http_protocol.h ../include/http_log.h \
 ../include/http_main.h ../include/scoreboard.h ../include/fnmatch.h
http_vhost.o: http_vhost.c ../include/httpd.h ../include/conf.h \
 ../os/unix/os.h ../include/hsregex.h ../include/alloc.h \
 ../include/buff.h ../include/ap.h ../include/http_config.h \
 ../include/http_conf_globals.h ../include/http_log.h \
 ../include/http_vhost.h ../include/http_protocol.h
md5c.o: md5c.c ../include/conf.h ../os/unix/os.h ../include/hsregex.h \
 ../include/md5.h
rfc1413.o: rfc1413.c ../include/httpd.h ../include/conf.h \
 ../os/unix/os.h ../include/hsregex.h ../include/alloc.h \
 ../include/buff.h ../include/ap.h ../include/http_log.h \
 ../include/rfc1413.h ../include/http_main.h
util.o: util.c ../include/httpd.h ../include/conf.h ../os/unix/os.h \
 ../include/hsregex.h ../include/alloc.h ../include/buff.h \
 ../include/ap.h ../include/http_conf_globals.h ../include/http_log.h
util_date.o: util_date.c ../include/conf.h ../os/unix/os.h \
 ../include/hsregex.h ../include/util_date.h
util_md5.o: util_md5.c ../include/httpd.h ../include/conf.h \
 ../os/unix/os.h ../include/hsregex.h ../include/alloc.h \
 ../include/buff.h ../include/ap.h ../include/util_md5.h \
 ../include/md5.h
util_script.o: util_script.c ../include/httpd.h ../include/conf.h \
 ../os/unix/os.h ../include/hsregex.h ../include/alloc.h \
 ../include/buff.h ../include/ap.h ../include/http_config.h \
 ../include/http_conf_globals.h ../include/http_main.h \
 ../include/http_log.h ../include/http_protocol.h \
 ../include/http_core.h ../include/http_request.h \
 ../include/util_script.h ../include/util_date.h
