#!/bin/sh
echo " Setting TPF/c89 environment variables"
TZ=EST5EDT
PATH="$PATH:/usr/sbin:/usr/share/lib/terminfo/:.:/etc:$HOME"
NLSPATH=/usr/lpp/tcpip/usr/lib/nls/msg/%L:/usr/lib/nls/msg/%L/%N
LIBPATH=/usr/lib
LANG=C
export TZ PATH NLSPATH LANG
# Commands Reference
# umask g=rx,o=x
umask 022
    export _C89_CCMODE=1
    export _C89_CVERSION="0x21040000"
    export _C89_PVERSION="0x11080000"
    export _C89_CNAME="CBCDRVR"
    export _C89_PNAME="EDCPRLK"
    export _C89_PMSGS="EDCPMSGE"
    export _C89_CLIB_PREFIX="TSCTEST.OSV2R4M0"
    export _C89_PLIB_PREFIX="SHARE.CEE180"
    export _C89_INCDIRS="/u/tpf41/currentmaint/include /u/tpf41/currentmaint/include/oco //DD:SYSLIB //'SHARE.CEE180.SCEEH.NET.H' //'SHARE.CEE180.SCEEH.H' //'SHARE.CEE180.SCEEH.NETINET.H'" 
    export _C89_SSYSLIB=SHARE.CEE180.SCEEMAC
    export _C89_WORK_UNIT="VIO"
export _BPX_SHAREAS=YES
export PATH NLSPATH LIBPATH
export TPF=YES
echo "Done"
