top_srcdir   = /Users/jim/src/asf/code/dev/httpd-trunk
top_builddir = /Users/jim/src/asf/code/dev/httpd-trunk
srcdir       = /Users/jim/src/asf/code/dev/httpd-trunk/server/mpm
builddir     = /Users/jim/src/asf/code/dev/httpd-trunk/server/mpm
VPATH        = /Users/jim/src/asf/code/dev/httpd-trunk/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
