top_srcdir   = /home/ganwang/httpd/httpd
top_builddir = /home/ganwang/httpd/httpd
srcdir       = /home/ganwang/httpd/httpd/modules/apreq
builddir     = /home/ganwang/httpd/httpd/modules/apreq
VPATH        = /home/ganwang/httpd/httpd/modules/apreq
include $(top_srcdir)/build/special.mk
