top_srcdir   = /Users/jim/src/asf/code/dev/httpd-trunk
top_builddir = /Users/jim/src/asf/code/dev/httpd-trunk
srcdir       = /Users/jim/src/asf/code/dev/httpd-trunk/modules/aaa
builddir     = /Users/jim/src/asf/code/dev/httpd-trunk/modules/aaa
VPATH        = /Users/jim/src/asf/code/dev/httpd-trunk/modules/aaa

include $(top_srcdir)/build/special.mk

