
#Dependencies

$(OBJS) $(OBJS_PIC): Makefile

# DO NOT REMOVE
mod_rndchunk.o: mod_rndchunk.c $(INCDIR)/httpd.h \
 $(INCDIR)/conf.h ../../os/unix/os.h \
 $(INCDIR)/hsregex.h $(INCDIR)/alloc.h $(INCDIR)/buff.h \
 $(INCDIR)/ap.h $(INCDIR)/util_uri.h \
 $(INCDIR)/http_protocol.h $(INCDIR)/http_config.h \
 $(INCDIR)/http_main.h
mod_test_util_uri.o: mod_test_util_uri.c $(INCDIR)/httpd.h \
 $(INCDIR)/conf.h ../../os/unix/os.h \
 $(INCDIR)/hsregex.h $(INCDIR)/alloc.h $(INCDIR)/buff.h \
 $(INCDIR)/ap.h $(INCDIR)/util_uri.h \
 $(INCDIR)/http_protocol.h $(INCDIR)/http_config.h \
 $(INCDIR)/http_main.h
