#! /bin/sh
#
#. Created by configure
CC="gcc " \
"./configure" \
"--prefix=/usr/local2/apache2" \
"--enable-mods-static=most" \
"--enable-proxy" \
"--enable-proxy-fcgi" \
"--enable-maintainer-mode" \
"--with-included-apr" \
"--enable-substitute" \
"--enable-version" \
"--with-mpm=event" \
"$@"
