top_srcdir   = /home/ganwang/Documents/httpd
top_builddir = /home/ganwang/Documents/httpd
srcdir       = /home/ganwang/Documents/httpd/modules/arch/unix
builddir     = /home/ganwang/Documents/httpd/modules/arch/unix
VPATH        = /home/ganwang/Documents/httpd/modules/arch/unix

include $(top_srcdir)/build/special.mk

