##
##  Makefile -- mod_ssl User Manual: Build Precedure
##  Copyright (c) 1998-2001 Ralf S. Engelschall, All Rights Reserved. 
##

WMK = wmk

#   it's trivial because we use Website META Language (WML)
#   Make command to perform all building ;-)
all:
	$(WMK)

clean:
	-rm -f *.html

