top_srcdir   = /Users/jim/src/asf/code/dev/httpd-trunk
top_builddir = /Users/jim/src/asf/code/dev/httpd-trunk
srcdir       = /Users/jim/src/asf/code/dev/httpd-trunk/modules/echo
builddir     = /Users/jim/src/asf/code/dev/httpd-trunk/modules/echo
VPATH        = /Users/jim/src/asf/code/dev/httpd-trunk/modules/echo

include $(top_srcdir)/build/special.mk

