top_srcdir   = /Users/jim/src/asf/code/dev/httpd-trunk
top_builddir = /Users/jim/src/asf/code/dev/httpd-trunk
srcdir       = /Users/jim/src/asf/code/dev/httpd-trunk/modules/filters
builddir     = /Users/jim/src/asf/code/dev/httpd-trunk/modules/filters
VPATH        = /Users/jim/src/asf/code/dev/httpd-trunk/modules/filters

include $(top_srcdir)/build/special.mk

