#!/bin/sh
# Attempt to guess which C compiler we should use...

for path in `echo $PATH | sed "s/:/ /g"`
do
	if [ -x $path/gcc ]; then echo gcc; exit; fi
done
for path in `echo $PATH | sed "s/:/ /g"`
do
	if [ -x $path/cc ]; then echo cc; exit; fi
done