# Makefile for NT
# Note that this doesn't quite work... apache.exe doesn't depend on proxy.lib
# or regex.lib. Nor can it, without some messing about - the debug and release
# versions need different dependencies, and that isn't an option.
# One way that occurs to me to solve the problem is to have the proxy and
# regex makes delete the appropriate apache.exe. Tacky, but it'll work!
# Ben, 5 July 97

_debug:
    cd regex & set CFG=regex - Win32 Debug& nmake /nologo -f regex.mak
	cd . & set CFG=ApacheCore - Win32 Debug& nmake /nologo -f ApacheCore.mak
	cd . & set CFG=Apache - Win32 Debug& nmake /nologo -f Apache.mak
	cd nt & set CFG=ApacheModuleStatus - Win32 Debug& nmake /nologo -f ApacheModuleStatus.mak
#	cd nt & set CFG=ApacheModuleInfo - Win32 Debug& nmake /nologo -f ApacheModuleInfo.mak
	cd nt & set CFG=ApacheModuleAuthAnon - Win32 Debug& nmake /nologo -f ApacheModuleAuthAnon.mak
	cd nt & set CFG=ApacheModuleDigest - Win32 Debug& nmake /nologo -f ApacheModuleDigest.mak
	cd nt & set CFG=ApacheModuleCERNMeta - Win32 Debug& nmake /nologo -f ApacheModuleCERNMeta.mak
	cd nt & set CFG=ApacheModuleExpires - Win32 Debug& nmake /nologo -f ApacheModuleExpires.mak
	cd nt & set CFG=ApacheModuleHeaders - Win32 Debug& nmake /nologo -f ApacheModuleHeaders.mak
	cd nt & set CFG=ApacheModuleUserTrack - Win32 Debug& nmake /nologo -f ApacheModuleUserTrack.mak
	cd modules\proxy & set CFG=ApacheModuleProxy - Win32 Debug& nmake /nologo -f ApacheModuleProxy.mak


installd: _debug
	-mkdir \Apache
	-mkdir \Apache\modules
	copy ApacheD\Apache.exe \Apache
	copy CoreD\ApacheCore.dll \Apache
	copy nt\ApacheModuleStatusD\ApacheModuleStatus.dll \Apache\modules
#	copy nt\ApacheModuleInfoD\ApacheModuleInfo.dll \Apache\modules
	copy nt\ApacheModuleAuthAnonD\ApacheModuleAuthAnon.dll \Apache\modules
	copy nt\ApacheModuleDigestD\ApacheModuleDigest.dll \Apache\modules
	copy nt\ApacheModuleCERNMetaD\ApacheModuleCERNMeta.dll \Apache\modules
	copy nt\ApacheModuleExpiresD\ApacheModuleExpires.dll \Apache\modules
	copy nt\ApacheModuleHeadersD\ApacheModuleHeaders.dll \Apache\modules
	copy nt\ApacheModuleUserTrackD\ApacheModuleUserTrack.dll \Apache\modules
	copy modules\proxy\Debug\ApacheModuleProxy.dll \Apache\modules
