# Makefile for NT
# Note that this doesn't quite work... apache.exe doesn't depend on proxy.lib
# or regex.lib. Nor can it, without some messing about - the debug and release
# versions need different dependencies, and that isn't an option.
# One way that occurs to me to solve the problem is to have the proxy and
# regex makes delete the appropriate apache.exe. Tacky, but it'll work!
# Ben, 5 July 97

_debug:
    cd modules\proxy & set CFG=proxy - Win32 Debug& nmake -f proxy.mak
    cd regex & set CFG=regex - Win32 Debug& nmake -f regex.mak
	cd . & set CFG=ApacheCore - Win32 Debug& nmake -f ApacheCore.mak
	cd . & set CFG=ApacheLaunch - Win32 Debug& nmake -f ApacheLaunch.mak
	cd nt & set CFG=ApacheModuleStatus - Win32 Debug& nmake -f ApacheModuleStatus.mak
#	cd nt & set CFG=ApacheModuleInfo - Win32 Debug& nmake -f ApacheModuleInfo.mak
	cd nt & set CFG=ApacheModuleAuthAnon - Win32 Debug& nmake -f ApacheModuleAuthAnon.mak
	cd nt & set CFG=ApacheModuleDigest - Win32 Debug& nmake -f ApacheModuleDigest.mak
	cd nt & set CFG=ApacheModuleCERNMeta - Win32 Debug& nmake -f ApacheModuleCERNMeta.mak
	cd nt & set CFG=ApacheModuleExpires - Win32 Debug& nmake -f ApacheModuleExpires.mak
	cd nt & set CFG=ApacheModuleHeaders - Win32 Debug& nmake -f ApacheModuleHeaders.mak
	cd nt & set CFG=ApacheModuleUserTrack - Win32 Debug& nmake -f ApacheModuleUserTrack.mak


installd: _debug
	-mkdir \Apache
	copy LaunchD\ApacheLaunch.exe \Apache
	copy CoreD\ApacheCore.dll \Apache
	copy nt\ApacheModuleStatusD\ApacheModuleStatus.dll \Apache
#	copy nt\ApacheModuleInfoD\ApacheModuleInfo.dll \Apache
	copy nt\ApacheModuleAuthAnonD\ApacheModuleAuthAnon.dll \Apache
	copy nt\ApacheModuleDigestD\ApacheModuleDigest.dll \Apache
	copy nt\ApacheModuleCERNMetaD\ApacheModuleCERNMeta.dll \Apache
	copy nt\ApacheModuleExpiresD\ApacheModuleExpires.dll \Apache
	copy nt\ApacheModuleHeadersD\ApacheModuleHeaders.dll \Apache
	copy nt\ApacheModuleUserTrackD\ApacheModuleUserTrack.dll \Apache
