# Apache makefile template (well, suffix).

# This is combined with the information in the "Configuration" file
# by the configure script to make the actual Makefile.

CFLAGS=$(OPTIM) $(CFLAGS1) $(EXTRA_CFLAGS)
LIBS=$(EXTRA_LIBS) $(LIBS1)
INCLUDES=$(INCLUDES1) $(INCLUDES_DEPTH0) $(EXTRA_INCLUDES)
INCDIR=include
LDFLAGS=$(LDFLAGS1) $(EXTRA_LDFLAGS)

OBJS= \
  modules.o \
  $(MODULES) \
  main/libmain.a \
  $(OSDIR)/libos.a \
  ap/libap.a

.c.o:
	$(CC) -c $(INCLUDES) $(CFLAGS) $(SPACER) $<

all: @@Configuration@@ $(TARGET)

@@Configuration@@: Configuration.tmpl
	@echo "@@Configuration@@ older than Configuration.tmpl, or doesn't exist."
	@echo "Consider copying Configuration.tmpl to @@Configuration@@, editing and rerunning"
	@echo "Configure."
	@echo "If not, you will at least have to touch @@Configuration@@."
	@false

$(TARGET):  subdirs modules.o
	$(CC) -c $(INCLUDES) $(CFLAGS) $(SPACER) buildmark.c
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDFLAGS_SHLIB_EXPORT) -o $(TARGET) buildmark.o $(OBJS) $(REGLIB) $(LIBS)

subdirs:
	for i in $(SUBDIRS); do \
		( cd $$i && $(MAKE) CC='$(CC)' AUX_CFLAGS='$(CFLAGS)' RANLIB='$(RANLIB)') || exit 1; \
	done

support: support-dir

support-dir:
	cd support; $(MAKE) CC='$(CC)' AUX_CFLAGS='$(CFLAGS)' RANLIB='$(RANLIB)'

clean:
	rm -f $(TARGET) *.o *.bak
	for i in $(SUBDIRS); do \
		( cd $$i && $(MAKE) $@ ) || exit 1; \
	done

# We really don't expect end users to use this rule.  It works only with
# gcc, and rebuilds Makefile.tmpl.  You have to re-run Configure after
# using it.
depend:
	cp Makefile.tmpl Makefile.tmpl.bak \
	    && sed -ne '1,/^# DO NOT REMOVE/p' Makefile.tmpl > Makefile.new \
	    && gcc -MM $(INCLUDES) $(CFLAGS) *.c >> Makefile.new \
	    && sed -e '1,$$s: $(INCDIR)/: $$(INCDIR)/:g' Makefile.new \
		> Makefile.tmpl \
	    && rm Makefile.new
	for i in $(SUBDIRS); do \
	    ( cd $$i && $(MAKE) CC='$(CC)' AUX_CFLAGS='$(CFLAGS)' RANLIB='$(RANLIB)' depend ) || exit 1; \
	done

# We really don't expect end users to use this rule. It builds a
# httpd binary with all modules built in and then updates the
# $(INCDIR)/hide.h file according to the exported symbols of this
# binary. So run this target once after a new function was added
# to the source.
updatehide:
	cat Configuration.tmpl |\
        sed -e 's/^#*[ 	]*\(AddModule\)/\1/g' |\
        cat >Configuration.for-hide
	$(MAKE) clean 
	./Configure -file Configuration.for-hide
	$(MAKE) httpd
	./helpers/UpdateHide httpd $(INCDIR)/hide.h
	$(MAKE) clean
	rm -f Configuration.for-hide

#Dependencies

$(OBJS): Makefile

# DO NOT REMOVE
buildmark.o: buildmark.c $(INCDIR)/conf.h os/unix/os.h $(INCDIR)/hsregex.h
modules.o: modules.c $(INCDIR)/httpd.h $(INCDIR)/conf.h os/unix/os.h \
 $(INCDIR)/hsregex.h $(INCDIR)/alloc.h $(INCDIR)/buff.h $(INCDIR)/ap.h \
 $(INCDIR)/util_uri.h $(INCDIR)/http_config.h
