top_srcdir   = /Users/jim/src/asf/code/dev/httpd-trunk
top_builddir = /Users/jim/src/asf/code/dev/httpd-trunk
srcdir       = /Users/jim/src/asf/code/dev/httpd-trunk/modules/cache
builddir     = /Users/jim/src/asf/code/dev/httpd-trunk/modules/cache
VPATH        = /Users/jim/src/asf/code/dev/httpd-trunk/modules/cache

include $(top_srcdir)/build/special.mk

