# We really don't expect end users to use this rule.  It works only with
# gcc, and rebuilds Makefile.tmpl.  You have to re-run Configure after
# using it.
depend:
	sed -ne '1,/^# DO NOT REMOVE/p' Makefile.tmpl > Makefile.new \
	    && $(CC) -MM $(INCLUDES) $(CFLAGS) *.c >> Makefile.new \
	    && mv Makefile.tmpl Makefile.tmpl.bak \
	    && mv Makefile.new Makefile.tmpl

#Dependencies

$(OBJS): Makefile

# DO NOT REMOVE
mod_access.o: mod_access.c ../../include/httpd.h ../../include/conf.h \
 ../../os/unix/os.h ../../include/hsregex.h ../../include/alloc.h \
 ../../include/buff.h ../../include/ap.h ../../include/http_core.h \
 ../../include/http_config.h ../../include/http_log.h \
 ../../include/http_request.h
mod_actions.o: mod_actions.c ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h ../../include/http_request.h \
 ../../include/http_core.h ../../include/http_protocol.h \
 ../../include/http_main.h ../../include/http_log.h \
 ../../include/util_script.h
mod_alias.o: mod_alias.c ../../include/httpd.h ../../include/conf.h \
 ../../os/unix/os.h ../../include/hsregex.h ../../include/alloc.h \
 ../../include/buff.h ../../include/ap.h ../../include/http_config.h
mod_asis.o: mod_asis.c ../../include/httpd.h ../../include/conf.h \
 ../../os/unix/os.h ../../include/hsregex.h ../../include/alloc.h \
 ../../include/buff.h ../../include/ap.h ../../include/http_config.h \
 ../../include/http_protocol.h ../../include/http_log.h \
 ../../include/util_script.h ../../include/http_main.h \
 ../../include/http_request.h
mod_auth.o: mod_auth.c ../../include/httpd.h ../../include/conf.h \
 ../../os/unix/os.h ../../include/hsregex.h ../../include/alloc.h \
 ../../include/buff.h ../../include/ap.h ../../include/http_config.h \
 ../../include/http_core.h ../../include/http_log.h \
 ../../include/http_protocol.h
mod_auth_anon.o: mod_auth_anon.c ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h ../../include/http_core.h \
 ../../include/http_log.h ../../include/http_protocol.h \
 ../../include/http_request.h
mod_auth_db.o: mod_auth_db.c ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h ../../include/http_core.h \
 ../../include/http_log.h ../../include/http_protocol.h
mod_auth_dbm.o: mod_auth_dbm.c ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h ../../include/http_core.h \
 ../../include/http_log.h ../../include/http_protocol.h
mod_autoindex.o: mod_autoindex.c ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h ../../include/http_core.h \
 ../../include/http_request.h ../../include/http_protocol.h \
 ../../include/http_log.h ../../include/http_main.h \
 ../../include/util_script.h
mod_cern_meta.o: mod_cern_meta.c ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h ../../include/util_script.h \
 ../../include/http_log.h ../../include/http_request.h
mod_cgi.o: mod_cgi.c ../../include/httpd.h ../../include/conf.h \
 ../../os/unix/os.h ../../include/hsregex.h ../../include/alloc.h \
 ../../include/buff.h ../../include/ap.h ../../include/http_config.h \
 ../../include/http_request.h ../../include/http_core.h \
 ../../include/http_protocol.h ../../include/http_main.h \
 ../../include/http_log.h ../../include/util_script.h \
 ../../include/http_conf_globals.h
mod_digest.o: mod_digest.c ../../include/httpd.h ../../include/conf.h \
 ../../os/unix/os.h ../../include/hsregex.h ../../include/alloc.h \
 ../../include/buff.h ../../include/ap.h ../../include/http_config.h \
 ../../include/http_core.h ../../include/http_log.h \
 ../../include/http_protocol.h ../../include/util_md5.h \
 ../../include/md5.h
mod_dir.o: mod_dir.c ../../include/httpd.h ../../include/conf.h \
 ../../os/unix/os.h ../../include/hsregex.h ../../include/alloc.h \
 ../../include/buff.h ../../include/ap.h ../../include/http_config.h \
 ../../include/http_core.h ../../include/http_request.h \
 ../../include/http_protocol.h ../../include/http_log.h \
 ../../include/http_main.h ../../include/util_script.h
mod_env.o: mod_env.c ../../include/httpd.h ../../include/conf.h \
 ../../os/unix/os.h ../../include/hsregex.h ../../include/alloc.h \
 ../../include/buff.h ../../include/ap.h ../../include/http_config.h
mod_expires.o: mod_expires.c ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h ../../include/http_log.h
mod_headers.o: mod_headers.c ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h
mod_imap.o: mod_imap.c ../../include/httpd.h ../../include/conf.h \
 ../../os/unix/os.h ../../include/hsregex.h ../../include/alloc.h \
 ../../include/buff.h ../../include/ap.h ../../include/http_config.h \
 ../../include/http_request.h ../../include/http_core.h \
 ../../include/http_protocol.h ../../include/http_main.h \
 ../../include/http_log.h ../../include/util_script.h
mod_include.o: mod_include.c ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h ../../include/http_request.h \
 ../../include/http_core.h ../../include/http_protocol.h \
 ../../include/http_log.h ../../include/http_main.h \
 ../../include/util_script.h
mod_info.o: mod_info.c ../../include/httpd.h ../../include/conf.h \
 ../../os/unix/os.h ../../include/hsregex.h ../../include/alloc.h \
 ../../include/buff.h ../../include/ap.h ../../include/http_config.h \
 ../../include/http_core.h ../../include/http_log.h \
 ../../include/http_main.h ../../include/http_protocol.h \
 ../../include/util_script.h ../../include/http_conf_globals.h
mod_log_agent.o: mod_log_agent.c ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h
mod_log_config.o: mod_log_config.c ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h ../../include/http_core.h \
 ../../include/http_log.h
mod_log_referer.o: mod_log_referer.c ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h
mod_mime.o: mod_mime.c ../../include/httpd.h ../../include/conf.h \
 ../../os/unix/os.h ../../include/hsregex.h ../../include/alloc.h \
 ../../include/buff.h ../../include/ap.h ../../include/http_config.h \
 mod_mime.h
mod_mime_magic.o: mod_mime_magic.c ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h ../../include/http_request.h \
 ../../include/http_core.h ../../include/http_log.h \
 ../../include/http_protocol.h
mod_negotiation.o: mod_negotiation.c ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h ../../include/http_request.h \
 ../../include/http_core.h ../../include/http_log.h \
 ../../include/util_script.h
mod_rewrite.o: mod_rewrite.c ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h ../../include/http_request.h \
 ../../include/http_core.h ../../include/http_log.h mod_rewrite.h
mod_setenvif.o: mod_setenvif.c ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h ../../include/http_core.h \
 ../../include/http_log.h
mod_so.o: mod_so.c ../../include/httpd.h ../../include/conf.h \
 ../../os/unix/os.h ../../include/hsregex.h ../../include/alloc.h \
 ../../include/buff.h ../../include/ap.h ../../include/http_config.h \
 ../../include/http_log.h
mod_speling.o: mod_speling.c ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_core.h ../../include/http_config.h \
 ../../include/http_log.h
mod_status.o: mod_status.c ../../include/httpd.h ../../include/conf.h \
 ../../os/unix/os.h ../../include/hsregex.h ../../include/alloc.h \
 ../../include/buff.h ../../include/ap.h ../../include/http_config.h \
 ../../include/http_core.h ../../include/http_protocol.h \
 ../../include/http_main.h ../../include/util_script.h \
 ../../include/scoreboard.h ../../include/http_log.h
mod_unique_id.o: mod_unique_id.c ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h ../../include/http_log.h \
 ../../include/multithread.h
mod_userdir.o: mod_userdir.c ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h
mod_usertrack.o: mod_usertrack.c ../../include/httpd.h \
 ../../include/conf.h ../../os/unix/os.h ../../include/hsregex.h \
 ../../include/alloc.h ../../include/buff.h ../../include/ap.h \
 ../../include/http_config.h ../../include/http_core.h
