top_srcdir   = /home/ganwang/httpd/httpd
top_builddir = /home/ganwang/httpd/httpd
srcdir       = /home/ganwang/httpd/httpd/modules/http
builddir     = /home/ganwang/httpd/httpd/modules/http
VPATH        = /home/ganwang/httpd/httpd/modules/http

include $(top_srcdir)/build/special.mk

