top_srcdir   = /Users/jim/src/asf/code/dev/httpd-trunk
top_builddir = /Users/jim/src/asf/code/dev/httpd-trunk
srcdir       = /Users/jim/src/asf/code/dev/httpd-trunk/os
builddir     = /Users/jim/src/asf/code/dev/httpd-trunk/os
VPATH        = /Users/jim/src/asf/code/dev/httpd-trunk/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
