#!/bin/sh
echo " Setting TPF41/c89 environment variables"
export _C89_CCMODE=1
# replace the following with the location of your TPF41 include files
export _C89_INCDIRS="/u/tpf41/rlse/include"
export TPF=YES
export _C89_INCLIBS=""
export _C89_CSYSLIB=""
export _C89_OPTIONS="-W 0,langlvl(extended)"
echo "Done"
