top_srcdir   = /Users/jim/src/asf/code/dev/httpd-trunk
top_builddir = /Users/jim/src/asf/code/dev/httpd-trunk
srcdir       = /Users/jim/src/asf/code/dev/httpd-trunk/modules/generators
builddir     = /Users/jim/src/asf/code/dev/httpd-trunk/modules/generators
VPATH        = /Users/jim/src/asf/code/dev/httpd-trunk/modules/generators

include $(top_srcdir)/build/special.mk

