top_srcdir   = /home/ganwang/httpd/httpd
top_builddir = /home/ganwang/httpd/httpd
srcdir       = /home/ganwang/httpd/httpd/server/mpm
builddir     = /home/ganwang/httpd/httpd/server/mpm
VPATH        = /home/ganwang/httpd/httpd/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
